### ISSUE TITLE
Incompatible action space with AitW

### ISSUE THREAD

**Issue by Jiayi-Pan** [cooelf/Auto-UI#4]
Dear authors, thank you for this great work!
I wonder if the task_Impossible action defined in the original AitW paper is also applicable in this paper?

**Comment by Jiayi-Pan** [comment]
And if you've removed these task_impossible trajectories, could you clarify how did you evaluate the models on AitW?
Thanks :)

**Comment by cooelf** [comment]
Hi, our action space is the same as AITW (see https://github.com/cooelf/Auto-UI/blob/main/action_type.py). We did not remove any trajectory. After checking the model output, we could see 'action_type': '11', which means 'task_impossible'. 

Did the description from the paper cause your misunderstanding? We would make the paper more clear :)

**Comment by Jiayi-Pan** [comment]
Thank you for the clarification. It would be great if you can refine the state at page 5 `We consider six action types: dual-point gesture, type, go_back, go_home, enter, and status_complete.` :)
