### ISSUE TITLE
Inquiry about the train/dev/test split

### ISSUE THREAD

**Issue by Yangyi-Chen** [cooelf/Auto-UI#5]
Hi Zhuosheng,

Nice work! I'd like to follow this work and for a fair comparison, could you please provide some information about the train/dev/test split since I need to locate the original data? Thanks!

**Comment by cooelf** [comment]
Hi Yangyi,

Thanks for your interest. You can refer to https://github.com/cooelf/Auto-UI/tree/main/dataset for the data split. The files contain the episode ID that you can use to fetch the original dataset.

**Comment by Yangyi-Chen** [comment]
Thanks so much!
